namespace CodexVBE
{
    internal sealed partial class AboutWindow
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel rootLayout;
        private System.Windows.Forms.TableLayoutPanel headerLayout;
        private System.Windows.Forms.PictureBox brandImage;
        private System.Windows.Forms.Label productName;
        private System.Windows.Forms.Label tagline;
        private System.Windows.Forms.Label description;
        private CodexVBE.ChatComposerPanel detailsLayout;
        private System.Windows.Forms.Label versionLabel;
        private System.Windows.Forms.Label versionValue;
        private System.Windows.Forms.Label hostLabel;
        private System.Windows.Forms.Label hostValue;
        private System.Windows.Forms.Label platformLabel;
        private System.Windows.Forms.Label platformValue;
        private System.Windows.Forms.Label languageLabel;
        private System.Windows.Forms.Label languageValue;
        private System.Windows.Forms.FlowLayoutPanel resourceLinks;
        private System.Windows.Forms.LinkLabel projectLink;
        private System.Windows.Forms.LinkLabel documentationLink;
        private System.Windows.Forms.LinkLabel issuesLink;
        private System.Windows.Forms.TableLayoutPanel footerLayout;
        private System.Windows.Forms.Label status;
        private System.Windows.Forms.FlowLayoutPanel buttonLayout;
        private CodexVBE.ChatActionButton copyDetails;
        private CodexVBE.ChatActionButton closeButton;
        /// <summary>Libère les composants visuels et les abonnements de thème.</summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing) { DisposeRuntime(); if (brandImage.Image != null) { brandImage.Image.Dispose(); brandImage.Image = null; } components?.Dispose(); }
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AboutWindow));
            this.rootLayout = new System.Windows.Forms.TableLayoutPanel();
            this.headerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.brandImage = new System.Windows.Forms.PictureBox();
            this.productName = new System.Windows.Forms.Label();
            this.tagline = new System.Windows.Forms.Label();
            this.description = new System.Windows.Forms.Label();
            this.detailsLayout = new CodexVBE.ChatComposerPanel();
            this.versionLabel = new System.Windows.Forms.Label();
            this.versionValue = new System.Windows.Forms.Label();
            this.hostLabel = new System.Windows.Forms.Label();
            this.hostValue = new System.Windows.Forms.Label();
            this.platformLabel = new System.Windows.Forms.Label();
            this.platformValue = new System.Windows.Forms.Label();
            this.languageLabel = new System.Windows.Forms.Label();
            this.languageValue = new System.Windows.Forms.Label();
            this.resourceLinks = new System.Windows.Forms.FlowLayoutPanel();
            this.projectLink = new System.Windows.Forms.LinkLabel();
            this.documentationLink = new System.Windows.Forms.LinkLabel();
            this.issuesLink = new System.Windows.Forms.LinkLabel();
            this.footerLayout = new System.Windows.Forms.TableLayoutPanel();
            this.status = new System.Windows.Forms.Label();
            this.buttonLayout = new System.Windows.Forms.FlowLayoutPanel();
            this.copyDetails = new CodexVBE.ChatActionButton();
            this.closeButton = new CodexVBE.ChatActionButton();
            this.toolTips = new System.Windows.Forms.ToolTip(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.brandImage)).BeginInit();
            this.rootLayout.SuspendLayout();
            this.headerLayout.SuspendLayout();
            this.detailsLayout.SuspendLayout();
            this.resourceLinks.SuspendLayout();
            this.footerLayout.SuspendLayout();
            this.buttonLayout.SuspendLayout();
            this.SuspendLayout();
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.TabIndex = 0;
            this.rootLayout.Location = new System.Drawing.Point(0, 0);
            this.rootLayout.Size = new System.Drawing.Size(100, 24);
            this.headerLayout.Name = "headerLayout";
            this.headerLayout.TabIndex = 1;
            this.headerLayout.Location = new System.Drawing.Point(0, 0);
            this.headerLayout.Size = new System.Drawing.Size(100, 24);
            this.brandImage.Name = "brandImage";
            this.brandImage.TabIndex = 2;
            this.brandImage.Location = new System.Drawing.Point(0, 0);
            this.brandImage.Size = new System.Drawing.Size(100, 24);
            this.productName.Name = "productName";
            this.productName.TabIndex = 3;
            this.productName.Location = new System.Drawing.Point(0, 0);
            this.productName.Size = new System.Drawing.Size(100, 24);
            this.tagline.Name = "tagline";
            this.tagline.TabIndex = 4;
            this.tagline.Location = new System.Drawing.Point(0, 0);
            this.tagline.Size = new System.Drawing.Size(100, 24);
            this.description.Name = "description";
            this.description.TabIndex = 5;
            this.description.Location = new System.Drawing.Point(0, 0);
            this.description.Size = new System.Drawing.Size(100, 24);
            this.detailsLayout.Name = "detailsLayout";
            this.detailsLayout.TabIndex = 6;
            this.detailsLayout.Location = new System.Drawing.Point(0, 0);
            this.detailsLayout.Size = new System.Drawing.Size(100, 24);
            this.versionLabel.Name = "versionLabel";
            this.versionLabel.TabIndex = 7;
            this.versionLabel.Location = new System.Drawing.Point(0, 0);
            this.versionLabel.Size = new System.Drawing.Size(100, 24);
            this.versionValue.Name = "versionValue";
            this.versionValue.TabIndex = 8;
            this.versionValue.Location = new System.Drawing.Point(0, 0);
            this.versionValue.Size = new System.Drawing.Size(100, 24);
            this.hostLabel.Name = "hostLabel";
            this.hostLabel.TabIndex = 9;
            this.hostLabel.Location = new System.Drawing.Point(0, 0);
            this.hostLabel.Size = new System.Drawing.Size(100, 24);
            this.hostValue.Name = "hostValue";
            this.hostValue.TabIndex = 10;
            this.hostValue.Location = new System.Drawing.Point(0, 0);
            this.hostValue.Size = new System.Drawing.Size(100, 24);
            this.platformLabel.Name = "platformLabel";
            this.platformLabel.TabIndex = 11;
            this.platformLabel.Location = new System.Drawing.Point(0, 0);
            this.platformLabel.Size = new System.Drawing.Size(100, 24);
            this.platformValue.Name = "platformValue";
            this.platformValue.TabIndex = 12;
            this.platformValue.Location = new System.Drawing.Point(0, 0);
            this.platformValue.Size = new System.Drawing.Size(100, 24);
            this.languageLabel.Name = "languageLabel";
            this.languageLabel.TabIndex = 13;
            this.languageLabel.Location = new System.Drawing.Point(0, 0);
            this.languageLabel.Size = new System.Drawing.Size(100, 24);
            this.languageValue.Name = "languageValue";
            this.languageValue.TabIndex = 14;
            this.languageValue.Location = new System.Drawing.Point(0, 0);
            this.languageValue.Size = new System.Drawing.Size(100, 24);
            this.resourceLinks.Name = "resourceLinks";
            this.resourceLinks.TabIndex = 15;
            this.resourceLinks.Location = new System.Drawing.Point(0, 0);
            this.resourceLinks.Size = new System.Drawing.Size(100, 24);
            this.projectLink.Name = "projectLink";
            this.projectLink.TabIndex = 16;
            this.projectLink.Location = new System.Drawing.Point(0, 0);
            this.projectLink.Size = new System.Drawing.Size(100, 24);
            this.documentationLink.Name = "documentationLink";
            this.documentationLink.TabIndex = 17;
            this.documentationLink.Location = new System.Drawing.Point(0, 0);
            this.documentationLink.Size = new System.Drawing.Size(100, 24);
            this.issuesLink.Name = "issuesLink";
            this.issuesLink.TabIndex = 18;
            this.issuesLink.Location = new System.Drawing.Point(0, 0);
            this.issuesLink.Size = new System.Drawing.Size(100, 24);
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.TabIndex = 19;
            this.footerLayout.Location = new System.Drawing.Point(0, 0);
            this.footerLayout.Size = new System.Drawing.Size(100, 24);
            this.status.Name = "status";
            this.status.TabIndex = 20;
            this.status.Location = new System.Drawing.Point(0, 0);
            this.status.Size = new System.Drawing.Size(100, 24);
            this.buttonLayout.Name = "buttonLayout";
            this.buttonLayout.TabIndex = 21;
            this.buttonLayout.Location = new System.Drawing.Point(0, 0);
            this.buttonLayout.Size = new System.Drawing.Size(100, 24);
            this.copyDetails.Name = "copyDetails";
            this.copyDetails.TabIndex = 22;
            this.copyDetails.Location = new System.Drawing.Point(0, 0);
            this.copyDetails.Size = new System.Drawing.Size(100, 24);
            this.closeButton.Name = "closeButton";
            this.closeButton.TabIndex = 23;
            this.closeButton.Location = new System.Drawing.Point(0, 0);
            this.closeButton.Size = new System.Drawing.Size(100, 24);
            this.rootLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rootLayout.Padding = new System.Windows.Forms.Padding(28);
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.RowCount = 6;
            this.rootLayout.Size = new System.Drawing.Size(640, 504);
            this.rootLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.rootLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.rootLayout.Controls.Add(this.headerLayout, 0, 0);
            this.rootLayout.Controls.Add(this.description, 0, 1);
            this.rootLayout.Controls.Add(this.detailsLayout, 0, 2);
            this.rootLayout.Controls.Add(this.resourceLinks, 0, 3);
            this.rootLayout.Controls.Add(this.footerLayout, 0, 5);
            this.headerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.headerLayout.AutoSize = true;
            this.headerLayout.ColumnCount = 2;
            this.headerLayout.RowCount = 2;
            this.headerLayout.Margin = new System.Windows.Forms.Padding(0, 0, 0, 18);
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 106F));
            this.headerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.headerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.headerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.headerLayout.Controls.Add(this.brandImage, 0, 0);
            this.headerLayout.SetRowSpan(this.brandImage, 2);
            this.headerLayout.Controls.Add(this.productName, 1, 0);
            this.headerLayout.Controls.Add(this.tagline, 1, 1);
            this.brandImage.Image = ((System.Drawing.Image)(resources.GetObject("brandImage.Image")));
            this.brandImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.brandImage.Size = new System.Drawing.Size(88, 88);
            this.brandImage.Margin = new System.Windows.Forms.Padding(0, 0, 18, 0);
            this.brandImage.TabStop = false;
            this.productName.Text = "VBAi";
            this.productName.AutoSize = true;
            this.productName.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tagline.Text = "Your AI agent for VBA";
            this.tagline.AutoSize = true;
            this.tagline.Dock = System.Windows.Forms.DockStyle.Fill;
            this.description.Text = "Understand, edit and version your VBA projects with AI.";
            this.description.AutoSize = true;
            this.description.Dock = System.Windows.Forms.DockStyle.Fill;
            this.productName.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.productName.Margin = new System.Windows.Forms.Padding(0);
            this.tagline.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.tagline.Margin = new System.Windows.Forms.Padding(2, 0, 0, 6);
            this.description.Margin = new System.Windows.Forms.Padding(0, 0, 0, 20);
            this.description.MaximumSize = new System.Drawing.Size(580, 0);
            this.detailsLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.detailsLayout.AutoSize = true;
            this.detailsLayout.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.detailsLayout.ColumnCount = 2;
            this.detailsLayout.RowCount = 4;
            this.detailsLayout.Padding = new System.Windows.Forms.Padding(16);
            this.detailsLayout.Margin = new System.Windows.Forms.Padding(0);
            this.detailsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.detailsLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.detailsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.detailsLayout.Controls.Add(this.versionLabel, 0, 0);
            this.versionLabel.Text = "Version";
            this.versionLabel.AutoSize = true;
            this.versionLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.versionLabel.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.detailsLayout.Controls.Add(this.versionValue, 1, 0);
            this.versionValue.Text = "0.1.0.0";
            this.versionValue.AutoSize = true;
            this.versionValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.versionValue.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.versionValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.versionValue.AccessibleName = "Version";
            this.detailsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.detailsLayout.Controls.Add(this.hostLabel, 0, 1);
            this.hostLabel.Text = "Host";
            this.hostLabel.AutoSize = true;
            this.hostLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.hostLabel.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.detailsLayout.Controls.Add(this.hostValue, 1, 1);
            this.hostValue.Text = "Visual Basic Editor";
            this.hostValue.AutoSize = true;
            this.hostValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.hostValue.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.hostValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.hostValue.AccessibleName = "Host";
            this.detailsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.detailsLayout.Controls.Add(this.platformLabel, 0, 2);
            this.platformLabel.Text = "Platform";
            this.platformLabel.AutoSize = true;
            this.platformLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.platformLabel.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.detailsLayout.Controls.Add(this.platformValue, 1, 2);
            this.platformValue.Text = "Windows · x64 · .NET Framework 4.8";
            this.platformValue.AutoSize = true;
            this.platformValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.platformValue.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.platformValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.platformValue.AccessibleName = "Platform";
            this.detailsLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.detailsLayout.Controls.Add(this.languageLabel, 0, 3);
            this.languageLabel.Text = "Interface language";
            this.languageLabel.AutoSize = true;
            this.languageLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.languageLabel.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.detailsLayout.Controls.Add(this.languageValue, 1, 3);
            this.languageValue.Text = "English";
            this.languageValue.AutoSize = true;
            this.languageValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.languageValue.Margin = new System.Windows.Forms.Padding(3, 7, 3, 7);
            this.languageValue.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.languageValue.AccessibleName = "Interface language";
            this.resourceLinks.Dock = System.Windows.Forms.DockStyle.Fill;
            this.resourceLinks.AutoSize = true;
            this.resourceLinks.Margin = new System.Windows.Forms.Padding(0, 14, 0, 0);
            this.resourceLinks.WrapContents = true;
            this.resourceLinks.Controls.Add(this.projectLink);
            this.projectLink.Text = "Project on GitHub";
            this.projectLink.AutoSize = true;
            this.projectLink.Margin = new System.Windows.Forms.Padding(0, 6, 22, 6);
            this.projectLink.Tag = "https://github.com/blackcancer/CodexVBE";
            this.projectLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.projectLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ResourceLink_Click);
            this.toolTips.SetToolTip(this.projectLink, "https://github.com/blackcancer/CodexVBE");
            this.resourceLinks.Controls.Add(this.documentationLink);
            this.documentationLink.Text = "Documentation";
            this.documentationLink.AutoSize = true;
            this.documentationLink.Margin = new System.Windows.Forms.Padding(0, 6, 22, 6);
            this.documentationLink.Tag = "https://github.com/blackcancer/CodexVBE/tree/main/docs";
            this.documentationLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.documentationLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ResourceLink_Click);
            this.toolTips.SetToolTip(this.documentationLink, "https://github.com/blackcancer/CodexVBE/tree/main/docs");
            this.resourceLinks.Controls.Add(this.issuesLink);
            this.issuesLink.Text = "Report an issue";
            this.issuesLink.AutoSize = true;
            this.issuesLink.Margin = new System.Windows.Forms.Padding(0, 6, 22, 6);
            this.issuesLink.Tag = "https://github.com/blackcancer/CodexVBE/issues/new";
            this.issuesLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.issuesLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ResourceLink_Click);
            this.toolTips.SetToolTip(this.issuesLink, "https://github.com/blackcancer/CodexVBE/issues/new");
            this.footerLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footerLayout.AutoSize = true;
            this.footerLayout.ColumnCount = 1;
            this.footerLayout.RowCount = 2;
            this.footerLayout.Margin = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.footerLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.footerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.footerLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.footerLayout.Controls.Add(this.status, 0, 0);
            this.footerLayout.Controls.Add(this.buttonLayout, 0, 1);
            this.status.AutoSize = true;
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.MinimumSize = new System.Drawing.Size(0, 24);
            this.status.AccessibleRole = System.Windows.Forms.AccessibleRole.StatusBar;
            this.status.Margin = new System.Windows.Forms.Padding(0, 0, 0, 6);
            this.buttonLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonLayout.AutoSize = true;
            this.buttonLayout.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.buttonLayout.WrapContents = true;
            this.buttonLayout.Margin = new System.Windows.Forms.Padding(0);
            this.buttonLayout.Controls.Add(this.closeButton);
            this.closeButton.Text = "Close";
            this.closeButton.AutoSize = true;
            this.closeButton.MinimumSize = new System.Drawing.Size(100, 36);
            this.closeButton.Padding = new System.Windows.Forms.Padding(12, 6, 12, 6);
            this.closeButton.Margin = new System.Windows.Forms.Padding(8, 0, 0, 0);
            this.buttonLayout.Controls.Add(this.copyDetails);
            this.copyDetails.Text = "Copy technical details";
            this.copyDetails.AutoSize = true;
            this.copyDetails.MinimumSize = new System.Drawing.Size(170, 36);
            this.copyDetails.Padding = new System.Windows.Forms.Padding(12, 6, 12, 6);
            this.copyDetails.Margin = new System.Windows.Forms.Padding(8, 0, 0, 0);
            this.closeButton.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.copyDetails.Click += new System.EventHandler(this.CopyDetails_Click);
            this.toolTips.SetToolTip(this.copyDetails, "Copy the version and environment information for support.");
            this.AcceptButton = this.closeButton;
            this.CancelButton = this.closeButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(640, 504);
            this.MinimumSize = new System.Drawing.Size(620, 510);
            this.AutoSize = true;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowOnly;
            this.Controls.Add(this.rootLayout);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Name = "AboutWindow";
            this.Text = "About VBAi";
            ((System.ComponentModel.ISupportInitialize)(this.brandImage)).EndInit();
            this.buttonLayout.ResumeLayout(false);
            this.buttonLayout.PerformLayout();
            this.footerLayout.ResumeLayout(false);
            this.footerLayout.PerformLayout();
            this.resourceLinks.ResumeLayout(false);
            this.resourceLinks.PerformLayout();
            this.detailsLayout.ResumeLayout(false);
            this.detailsLayout.PerformLayout();
            this.headerLayout.ResumeLayout(false);
            this.headerLayout.PerformLayout();
            this.rootLayout.ResumeLayout(false);
            this.rootLayout.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.ToolTip toolTips;
    }
}
