namespace CodexVBE
{
    internal sealed partial class GitWindow
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.Label documentLabel;
        private System.Windows.Forms.Label remoteLabel;
        private System.Windows.Forms.Label branchLabel;
        private System.Windows.Forms.Label messageLabel;
        private System.Windows.Forms.Label help;
        private System.Windows.Forms.TextBox remote;
        private System.Windows.Forms.TextBox branch;
        private System.Windows.Forms.TextBox commitMessage;
        private System.Windows.Forms.Button connect;
        private System.Windows.Forms.Button commit;
        private System.Windows.Forms.Button fetch;
        private System.Windows.Forms.Label syncStatus;
        private System.Windows.Forms.TabControl tabs;
        private System.Windows.Forms.TabPage changesTab;
        private System.Windows.Forms.TabPage historyTab;
        private System.Windows.Forms.SplitContainer changeSplit;
        private System.Windows.Forms.DataGridView diff;
        private System.Windows.Forms.DataGridViewTextBoxColumn beforeColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn afterColumn;
        private System.Windows.Forms.ListBox history;
        private System.Windows.Forms.Button compare;
        private System.Windows.Forms.Button push;
        private System.Windows.Forms.Button pull;
        private System.Windows.Forms.Button restore;
        private System.Windows.Forms.FlowLayoutPanel actions;
        private System.Windows.Forms.ListBox changes;
        private System.Windows.Forms.Label status;
        private System.Windows.Forms.ToolTip toolTips;
        private System.Windows.Forms.TabPage branchesTab;
        private System.Windows.Forms.TabPage checkpointsTab;
        private System.Windows.Forms.TabPage conflictsTab;
        private System.Windows.Forms.FlowLayoutPanel branchActions;
        private System.Windows.Forms.FlowLayoutPanel checkpointActions;
        private System.Windows.Forms.FlowLayoutPanel conflictActions;
        private System.Windows.Forms.ListBox branchList;
        private System.Windows.Forms.ListBox checkpointList;
        private System.Windows.Forms.ListBox conflictList;
        private System.Windows.Forms.ComboBox branchName;
        private System.Windows.Forms.Button branchRemote;
        private System.Windows.Forms.TextBox checkpointName;
        private System.Windows.Forms.TextBox resolutionText;
        private System.Windows.Forms.Button branchCreate;
        private System.Windows.Forms.Button branchTrack;
        private System.Windows.Forms.Button branchSwitch;
        private System.Windows.Forms.Button mergeBegin;
        private System.Windows.Forms.Button checkpointCreate;
        private System.Windows.Forms.Button checkpointRestore;
        private System.Windows.Forms.Button mergeOurs;
        private System.Windows.Forms.Button mergeTheirs;
        private System.Windows.Forms.Button mergeText;
        private System.Windows.Forms.Button mergeComplete;
        private System.Windows.Forms.Button mergeAbort;
        private System.Windows.Forms.DataGridView conflictDiff;
        private System.Windows.Forms.DataGridViewTextBoxColumn conflictOurs;
        private System.Windows.Forms.DataGridViewTextBoxColumn conflictTheirs;

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GitWindow));
            this.components = new System.ComponentModel.Container();
            this.layout = new System.Windows.Forms.TableLayoutPanel();
            this.documentLabel = new System.Windows.Forms.Label();
            this.remoteLabel = new System.Windows.Forms.Label();
            this.branchLabel = new System.Windows.Forms.Label();
            this.messageLabel = new System.Windows.Forms.Label();
            this.help = new System.Windows.Forms.Label();
            this.remote = new System.Windows.Forms.TextBox();
            this.branch = new System.Windows.Forms.TextBox();
            this.commitMessage = new System.Windows.Forms.TextBox();
            this.connect = new System.Windows.Forms.Button();
            this.commit = new System.Windows.Forms.Button();
            this.fetch = new System.Windows.Forms.Button();
            this.syncStatus = new System.Windows.Forms.Label();
            this.tabs = new System.Windows.Forms.TabControl();
            this.changesTab = new System.Windows.Forms.TabPage();
            this.historyTab = new System.Windows.Forms.TabPage();
            this.changeSplit = new System.Windows.Forms.SplitContainer();
            this.diff = new System.Windows.Forms.DataGridView();
            this.beforeColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.afterColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.history = new System.Windows.Forms.ListBox();
            this.compare = new System.Windows.Forms.Button();
            this.push = new System.Windows.Forms.Button();
            this.pull = new System.Windows.Forms.Button();
            this.restore = new System.Windows.Forms.Button();
            this.actions = new System.Windows.Forms.FlowLayoutPanel();
            this.changes = new System.Windows.Forms.ListBox();
            this.status = new System.Windows.Forms.Label();
            this.toolTips = new System.Windows.Forms.ToolTip(this.components);
            this.branchesTab = new System.Windows.Forms.TabPage();
            this.checkpointsTab = new System.Windows.Forms.TabPage();
            this.conflictsTab = new System.Windows.Forms.TabPage();
            this.branchActions = new System.Windows.Forms.FlowLayoutPanel();
            this.checkpointActions = new System.Windows.Forms.FlowLayoutPanel();
            this.conflictActions = new System.Windows.Forms.FlowLayoutPanel();
            this.branchList = new System.Windows.Forms.ListBox();
            this.checkpointList = new System.Windows.Forms.ListBox();
            this.conflictList = new System.Windows.Forms.ListBox();
            this.branchName = new System.Windows.Forms.ComboBox();
            this.branchRemote = new System.Windows.Forms.Button();
            this.checkpointName = new System.Windows.Forms.TextBox();
            this.resolutionText = new System.Windows.Forms.TextBox();
            this.branchCreate = new System.Windows.Forms.Button();
            this.branchTrack = new System.Windows.Forms.Button();
            this.branchSwitch = new System.Windows.Forms.Button();
            this.mergeBegin = new System.Windows.Forms.Button();
            this.checkpointCreate = new System.Windows.Forms.Button();
            this.checkpointRestore = new System.Windows.Forms.Button();
            this.mergeOurs = new System.Windows.Forms.Button();
            this.mergeTheirs = new System.Windows.Forms.Button();
            this.mergeText = new System.Windows.Forms.Button();
            this.mergeComplete = new System.Windows.Forms.Button();
            this.mergeAbort = new System.Windows.Forms.Button();
            this.conflictDiff = new System.Windows.Forms.DataGridView();
            this.conflictOurs = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.conflictTheirs = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.branchActions.Name = "branchActions";
            this.checkpointActions.Name = "checkpointActions";
            this.conflictActions.Name = "conflictActions";
            this.branchCreate.Name = "branchCreate";
            this.branchRemote.Name = "branchRemote";
            this.branchTrack.Name = "branchTrack";
            this.branchSwitch.Name = "branchSwitch";
            this.mergeBegin.Name = "mergeBegin";
            this.checkpointCreate.Name = "checkpointCreate";
            this.checkpointRestore.Name = "checkpointRestore";
            this.mergeOurs.Name = "mergeOurs";
            this.mergeTheirs.Name = "mergeTheirs";
            this.mergeText.Name = "mergeText";
            this.mergeComplete.Name = "mergeComplete";
            this.mergeAbort.Name = "mergeAbort";
            this.conflictOurs.Name = "conflictOurs";
            this.conflictTheirs.Name = "conflictTheirs";
            this.layout.SuspendLayout();
            this.actions.SuspendLayout();
            this.SuspendLayout();
            // layout
            this.layout.ColumnCount = 2;
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 135F));
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowCount = 10;
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 68F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 45F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layout.Padding = new System.Windows.Forms.Padding(20);
            this.layout.Controls.Add(this.documentLabel, 0, 0);
            this.layout.SetColumnSpan(this.documentLabel, 2);
            this.layout.Controls.Add(this.help, 0, 1);
            this.layout.SetColumnSpan(this.help, 2);
            this.layout.Controls.Add(this.remoteLabel, 0, 2);
            this.layout.Controls.Add(this.remote, 1, 2);
            this.layout.Controls.Add(this.branchLabel, 0, 3);
            this.layout.Controls.Add(this.branch, 1, 3);
            this.layout.Controls.Add(this.connect, 1, 4);
            this.layout.Controls.Add(this.messageLabel, 0, 5);
            this.layout.Controls.Add(this.commitMessage, 1, 5);
            this.layout.Controls.Add(this.syncStatus, 0, 6);
            this.layout.SetColumnSpan(this.syncStatus, 2);
            this.layout.Controls.Add(this.actions, 0, 7);
            this.layout.SetColumnSpan(this.actions, 2);
            this.layout.Controls.Add(this.tabs, 0, 8);
            this.layout.SetColumnSpan(this.tabs, 2);
            this.layout.Controls.Add(this.status, 0, 9);
            this.layout.SetColumnSpan(this.status, 2);
            this.layout.Name = "layout";
            // documentLabel
            this.documentLabel.Text = "GitHub · sources VBA";
            this.documentLabel.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.documentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.documentLabel.AutoEllipsis = true;
            this.documentLabel.Name = "documentLabel";
            // help
            this.help.Text = "Les modifications du VBA deviennent des fichiers sources dans le dépôt. Aucun dossier à côté de la macro.\r\nLe premier pull remplace le VBA avec une sauvegarde restaurable.\r\nConnexion via Git Credential Manager ; identité de commit configurée dans Git.";
            this.help.Dock = System.Windows.Forms.DockStyle.Fill;
            this.help.Name = "help";
            // fields
            this.remoteLabel.Text = "Dépôt GitHub";
            this.remoteLabel.AutoSize = true;
            this.remoteLabel.Name = "remoteLabel";
            this.remote.Dock = System.Windows.Forms.DockStyle.Fill;
            this.remote.Name = "remote";
            this.remote.TabIndex = 0;
            this.toolTips.SetToolTip(this.remote, "URL HTTPS, par exemple https://github.com/organisation/macros.git. Ne collez aucun jeton.");
            this.branchLabel.Text = "Branche";
            this.branchLabel.AutoSize = true;
            this.branchLabel.Name = "branchLabel";
            this.branch.Text = "main";
            this.branch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.branch.Name = "branch";
            this.branch.TabIndex = 1;
            this.toolTips.SetToolTip(this.branch, "Branche à synchroniser. Les push ne sont jamais forcés.");
            this.connect.Text = "Lier le dépôt";
            this.connect.AutoSize = true;
            this.connect.Name = "connect";
            this.connect.TabIndex = 2;
            this.connect.Click += new System.EventHandler(this.Connect_Click);
            this.toolTips.SetToolTip(this.connect, "Mémorise la liaison pour ce document sur cet ordinateur. Ne publie aucun code.");
            this.messageLabel.Text = "Message de commit";
            this.messageLabel.AutoSize = true;
            this.messageLabel.Name = "messageLabel";
            this.commitMessage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.commitMessage.Multiline = true;
            this.commitMessage.Name = "commitMessage";
            this.commitMessage.TabIndex = 3;
            // actions
            this.actions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actions.Name = "actions";
            this.actions.Controls.Add(this.compare);
            this.actions.Controls.Add(this.commit);
            this.actions.Controls.Add(this.fetch);
            this.actions.Controls.Add(this.push);
            this.actions.Controls.Add(this.pull);
            this.actions.Controls.Add(this.restore);
            this.compare.Text = "Comparer";
            this.compare.AutoSize = true;
            this.compare.Enabled = false;
            this.compare.Name = "compare";
            this.compare.Click += new System.EventHandler(this.Compare_Click);
            this.toolTips.SetToolTip(this.compare, "Compare le VBA vivant au dernier état synchronisé, sans accès réseau.");
            this.commit.Text = "Commit (tout)";
            this.commit.AutoSize = true;
            this.commit.Enabled = false;
            this.commit.Name = "commit";
            this.commit.Click += new System.EventHandler(this.Commit_Click);
            this.toolTips.SetToolTip(this.commit, "Exporte les sources et crée un commit local de tous les changements. Push les publie ensuite.");
            this.fetch.Text = "Fetch";
            this.fetch.AutoSize = true;
            this.fetch.Enabled = false;
            this.fetch.Name = "fetch";
            this.fetch.Click += new System.EventHandler(this.Fetch_Click);
            this.toolTips.SetToolTip(this.fetch, "Actualise les commits distants et les compteurs sans modifier le VBA.");
            this.push.Text = "Push";
            this.push.AutoSize = true;
            this.push.Enabled = false;
            this.push.Name = "push";
            this.push.Click += new System.EventHandler(this.Push_Click);
            this.toolTips.SetToolTip(this.push, "Publie les commits locaux sur la branche choisie. Ne publie pas les modifications non commitées.");
            this.pull.Text = "Pull et importer";
            this.pull.AutoSize = true;
            this.pull.Enabled = false;
            this.pull.Name = "pull";
            this.pull.Click += new System.EventHandler(this.Pull_Click);
            this.toolTips.SetToolTip(this.pull, "Télécharge et importe les sources. Refuse les modifications locales non synchronisées et les historiques divergents.");
            this.restore.Text = "Restaurer VBA";
            this.restore.AutoSize = true;
            this.restore.Enabled = false;
            this.restore.Name = "restore";
            this.restore.Click += new System.EventHandler(this.Restore_Click);
            this.toolTips.SetToolTip(this.restore, "Restaure la sauvegarde avant le dernier import, si le VBA n’a pas été modifié depuis. Ne réécrit pas GitHub.");
            // changes and status
            this.changes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.changes.HorizontalScrollbar = true;
            this.changes.IntegralHeight = false;
            this.changes.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.changes.Name = "changes";
            this.changes.SelectedIndexChanged += new System.EventHandler(this.Changes_SelectedIndexChanged);
            this.syncStatus.Text = "Branche non liée";
            this.syncStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.syncStatus.Name = "syncStatus";
            this.tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabs.Name = "tabs";
            this.tabs.Controls.Add(this.changesTab);
            this.tabs.Controls.Add(this.historyTab);
            this.tabs.Controls.Add(this.branchesTab);
            this.tabs.Controls.Add(this.checkpointsTab);
            this.tabs.Controls.Add(this.conflictsTab);
            this.branchesTab.Text = "Branches";
            this.branchesTab.Name = "branchesTab";
            this.branchesTab.Enabled = false;
            this.branchesTab.Controls.Add(this.branchList);
            this.branchesTab.Controls.Add(this.branchActions);
            this.branchList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.branchList.Name = "branchList";
            this.branchActions.Dock = System.Windows.Forms.DockStyle.Top;
            this.branchActions.AutoSize = true;
            this.branchActions.Controls.Add(this.branchName);
            this.branchActions.Controls.Add(this.branchCreate);
            this.branchActions.Controls.Add(this.branchRemote);
            this.branchActions.Controls.Add(this.branchTrack);
            this.branchActions.Controls.Add(this.branchSwitch);
            this.branchActions.Controls.Add(this.mergeBegin);
            this.branchName.Width = 170;
            this.branchName.Name = "branchName";
            this.branchName.AccessibleName = "Nom de branche à créer ou récupérer";
            this.branchCreate.Text = "Créer";
            this.branchCreate.AutoSize = true;
            this.branchCreate.Click += new System.EventHandler(this.BranchCreate_Click);
            this.branchRemote.Text = "Distantes";
            this.branchRemote.AutoSize = true;
            this.branchRemote.Click += new System.EventHandler(this.RemoteBranches_Click);
            this.toolTips.SetToolTip(this.branchRemote, "Liste les branches du dépôt GitHub dans le sélecteur de nom, sans importer de VBA.");
            this.branchTrack.Text = "Récupérer distante";
            this.branchTrack.AutoSize = true;
            this.branchTrack.Click += new System.EventHandler(this.BranchTrack_Click);
            this.branchSwitch.Text = "Basculer";
            this.branchSwitch.AutoSize = true;
            this.branchSwitch.Click += new System.EventHandler(this.BranchSwitch_Click);
            this.mergeBegin.Text = "Fusionner";
            this.mergeBegin.AutoSize = true;
            this.mergeBegin.Click += new System.EventHandler(this.MergeBegin_Click);
            this.toolTips.SetToolTip(this.branchCreate, "Crée la branche saisie depuis le commit courant, sans la publier.");
            this.toolTips.SetToolTip(this.branchTrack, "Récupère la branche distante saisie, sans importer son VBA.");
            this.toolTips.SetToolTip(this.branchSwitch, "Importe la branche sélectionnée avec checkpoint préalable. Les modifications non commitées sont refusées.");
            this.toolTips.SetToolTip(this.mergeBegin, "Prépare la fusion de la branche sélectionnée vers la branche courante.");
            this.checkpointsTab.Text = "Checkpoints";
            this.checkpointsTab.Name = "checkpointsTab";
            this.checkpointsTab.Enabled = false;
            this.checkpointsTab.Controls.Add(this.checkpointList);
            this.checkpointsTab.Controls.Add(this.checkpointActions);
            this.checkpointList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.checkpointList.Name = "checkpointList";
            this.checkpointList.HorizontalScrollbar = true;
            this.checkpointActions.Dock = System.Windows.Forms.DockStyle.Top;
            this.checkpointActions.AutoSize = true;
            this.checkpointActions.Controls.Add(this.checkpointName);
            this.checkpointActions.Controls.Add(this.checkpointCreate);
            this.checkpointActions.Controls.Add(this.checkpointRestore);
            this.checkpointName.Width = 240;
            this.checkpointName.Name = "checkpointName";
            this.checkpointName.AccessibleName = "Nom du checkpoint";
            this.checkpointCreate.Text = "Créer un checkpoint";
            this.checkpointCreate.AutoSize = true;
            this.checkpointCreate.Click += new System.EventHandler(this.CheckpointCreate_Click);
            this.checkpointRestore.Text = "Restaurer la sélection";
            this.checkpointRestore.AutoSize = true;
            this.checkpointRestore.Click += new System.EventHandler(this.CheckpointRestore_Click);
            this.toolTips.SetToolTip(this.checkpointCreate, "Sauvegarde tout le VBA actuel dans un checkpoint privé, sans commit sur la branche publiée.");
            this.toolTips.SetToolTip(this.checkpointRestore, "Restaure le checkpoint choisi après sauvegarde de l’état courant. Ne réécrit pas GitHub.");
            this.conflictsTab.Text = "Conflits";
            this.conflictsTab.Name = "conflictsTab";
            this.conflictsTab.Enabled = false;
            this.conflictsTab.Controls.Add(this.resolutionText);
            this.conflictsTab.Controls.Add(this.conflictDiff);
            this.conflictsTab.Controls.Add(this.conflictList);
            this.conflictsTab.Controls.Add(this.conflictActions);
            this.conflictList.Dock = System.Windows.Forms.DockStyle.Top;
            this.conflictList.Height = 55;
            this.conflictList.Name = "conflictList";
            this.conflictList.SelectedIndexChanged += new System.EventHandler(this.ConflictList_SelectedIndexChanged);
            this.conflictDiff.Dock = System.Windows.Forms.DockStyle.Top;
            this.conflictDiff.Height = 110;
            this.conflictDiff.Name = "conflictDiff";
            this.conflictDiff.ReadOnly = true;
            this.conflictDiff.AllowUserToAddRows = false;
            this.conflictDiff.AllowUserToDeleteRows = false;
            this.conflictDiff.RowHeadersVisible = false;
            this.conflictDiff.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.conflictDiff.BackgroundColor = System.Drawing.Color.White;
            this.conflictDiff.Font = new System.Drawing.Font("Consolas", 9F);
            this.conflictDiff.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.conflictOurs, this.conflictTheirs });
            this.conflictOurs.HeaderText = "Branche courante";
            this.conflictOurs.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.conflictTheirs.HeaderText = "Branche entrante";
            this.conflictTheirs.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.resolutionText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.resolutionText.Multiline = true;
            this.resolutionText.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.resolutionText.WordWrap = false;
            this.resolutionText.Font = new System.Drawing.Font("Consolas", 9F);
            this.resolutionText.Name = "resolutionText";
            this.resolutionText.AccessibleName = "Contenu complet de résolution du fichier VBA sélectionné";
            this.conflictActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.conflictActions.AutoSize = true;
            this.conflictActions.Controls.Add(this.mergeOurs);
            this.conflictActions.Controls.Add(this.mergeTheirs);
            this.conflictActions.Controls.Add(this.mergeText);
            this.conflictActions.Controls.Add(this.mergeComplete);
            this.conflictActions.Controls.Add(this.mergeAbort);
            this.mergeOurs.Text = "Garder local";
            this.mergeOurs.AutoSize = true;
            this.mergeOurs.Click += new System.EventHandler(this.MergeOurs_Click);
            this.mergeTheirs.Text = "Garder entrant";
            this.mergeTheirs.AutoSize = true;
            this.mergeTheirs.Click += new System.EventHandler(this.MergeTheirs_Click);
            this.mergeText.Text = "Utiliser ce texte";
            this.mergeText.AutoSize = true;
            this.mergeText.Click += new System.EventHandler(this.MergeText_Click);
            this.mergeComplete.Text = "Terminer la fusion";
            this.mergeComplete.AutoSize = true;
            this.mergeComplete.Click += new System.EventHandler(this.MergeComplete_Click);
            this.mergeAbort.Text = "Annuler la fusion";
            this.mergeAbort.AutoSize = true;
            this.mergeAbort.Click += new System.EventHandler(this.MergeAbort_Click);
            this.toolTips.SetToolTip(this.mergeOurs, "Choisit le fichier entier de la branche courante pour le conflit sélectionné.");
            this.toolTips.SetToolTip(this.mergeTheirs, "Choisit le fichier entier de la branche entrante pour le conflit sélectionné.");
            this.toolTips.SetToolTip(this.mergeText, "Remplace le fichier VBA textuel entier par le texte édité ci-dessus.");
            this.toolTips.SetToolTip(this.mergeComplete, "Valide tous les fichiers, crée un commit de fusion puis importe le VBA avec sauvegarde.");
            this.toolTips.SetToolTip(this.mergeAbort, "Supprime uniquement la préparation de fusion. Le VBA et les commits restent intacts.");
            this.changesTab.Text = "Modifications Git";
            this.changesTab.Name = "changesTab";
            this.changesTab.Controls.Add(this.changeSplit);
            this.historyTab.Text = "Historique";
            this.historyTab.Name = "historyTab";
            this.historyTab.Controls.Add(this.history);
            this.history.Dock = System.Windows.Forms.DockStyle.Fill;
            this.history.HorizontalScrollbar = true;
            this.history.Name = "history";
            this.changeSplit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.changeSplit.Size = new System.Drawing.Size(860, 260);
            this.changeSplit.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.changeSplit.SplitterDistance = 200;
            this.changeSplit.Name = "changeSplit";
            this.changeSplit.Panel1.Controls.Add(this.changes);
            this.changeSplit.Panel2.Controls.Add(this.diff);
            this.diff.Dock = System.Windows.Forms.DockStyle.Fill;
            this.diff.ReadOnly = true;
            this.diff.AllowUserToAddRows = false;
            this.diff.AllowUserToDeleteRows = false;
            this.diff.AllowUserToOrderColumns = false;
            this.diff.RowHeadersVisible = false;
            this.diff.BackgroundColor = System.Drawing.Color.White;
            this.diff.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.diff.Font = new System.Drawing.Font("Consolas", 9F);
            this.diff.Name = "diff";
            this.diff.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.beforeColumn, this.afterColumn });
            this.beforeColumn.Name = "beforeColumn";
            this.beforeColumn.HeaderText = "Dernier commit / import";
            this.beforeColumn.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.beforeColumn.MinimumWidth = 280;
            this.afterColumn.Name = "afterColumn";
            this.afterColumn.HeaderText = "VBA actuel";
            this.afterColumn.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.afterColumn.MinimumWidth = 280;
            this.status.Text = "Liez un dépôt GitHub existant pour commencer.";
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.Padding = new System.Windows.Forms.Padding(0, 12, 0, 0);
            this.status.Name = "status";
            // window
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            this.ClientSize = new System.Drawing.Size(960, 780);
            this.MinimumSize = new System.Drawing.Size(900, 700);
            this.Controls.Add(this.layout);
            this.Name = "GitWindow";
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Text = "GitHub · VBAi";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.ShowInTaskbar = false;
            this.layout.ResumeLayout(false);
            this.layout.PerformLayout();
            this.actions.ResumeLayout(false);
            this.actions.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
