namespace CodexVBE
{
    internal sealed partial class GitWindow
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.Label documentLabel;
        private System.Windows.Forms.Label remoteLabel;
        private System.Windows.Forms.Label branchLabel;
        private System.Windows.Forms.Label messageLabel;
        private System.Windows.Forms.Label help;
        private System.Windows.Forms.TextBox remote;
        private System.Windows.Forms.TextBox branch;
        private System.Windows.Forms.TextBox commitMessage;
        private System.Windows.Forms.Button connect;
        private System.Windows.Forms.Button commit;
        private System.Windows.Forms.Button fetch;
        private System.Windows.Forms.Label syncStatus;
        private System.Windows.Forms.TabControl tabs;
        private System.Windows.Forms.TabPage changesTab;
        private System.Windows.Forms.TabPage historyTab;
        private System.Windows.Forms.SplitContainer changeSplit;
        private System.Windows.Forms.DataGridView diff;
        private System.Windows.Forms.DataGridViewTextBoxColumn beforeColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn afterColumn;
        private System.Windows.Forms.ListBox history;
        private System.Windows.Forms.Button compare;
        private System.Windows.Forms.Button push;
        private System.Windows.Forms.Button pull;
        private System.Windows.Forms.Button restore;
        private System.Windows.Forms.FlowLayoutPanel actions;
        private System.Windows.Forms.ListBox changes;
        private System.Windows.Forms.Label status;
        private System.Windows.Forms.ToolTip toolTips;

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.layout = new System.Windows.Forms.TableLayoutPanel();
            this.documentLabel = new System.Windows.Forms.Label();
            this.remoteLabel = new System.Windows.Forms.Label();
            this.branchLabel = new System.Windows.Forms.Label();
            this.messageLabel = new System.Windows.Forms.Label();
            this.help = new System.Windows.Forms.Label();
            this.remote = new System.Windows.Forms.TextBox();
            this.branch = new System.Windows.Forms.TextBox();
            this.commitMessage = new System.Windows.Forms.TextBox();
            this.connect = new System.Windows.Forms.Button();
            this.commit = new System.Windows.Forms.Button();
            this.fetch = new System.Windows.Forms.Button();
            this.syncStatus = new System.Windows.Forms.Label();
            this.tabs = new System.Windows.Forms.TabControl();
            this.changesTab = new System.Windows.Forms.TabPage();
            this.historyTab = new System.Windows.Forms.TabPage();
            this.changeSplit = new System.Windows.Forms.SplitContainer();
            this.diff = new System.Windows.Forms.DataGridView();
            this.beforeColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.afterColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.history = new System.Windows.Forms.ListBox();
            this.compare = new System.Windows.Forms.Button();
            this.push = new System.Windows.Forms.Button();
            this.pull = new System.Windows.Forms.Button();
            this.restore = new System.Windows.Forms.Button();
            this.actions = new System.Windows.Forms.FlowLayoutPanel();
            this.changes = new System.Windows.Forms.ListBox();
            this.status = new System.Windows.Forms.Label();
            this.toolTips = new System.Windows.Forms.ToolTip(this.components);
            this.layout.SuspendLayout();
            this.actions.SuspendLayout();
            this.SuspendLayout();
            // layout
            this.layout.ColumnCount = 2;
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 135F));
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowCount = 10;
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 68F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 45F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layout.Padding = new System.Windows.Forms.Padding(20);
            this.layout.Controls.Add(this.documentLabel, 0, 0);
            this.layout.SetColumnSpan(this.documentLabel, 2);
            this.layout.Controls.Add(this.help, 0, 1);
            this.layout.SetColumnSpan(this.help, 2);
            this.layout.Controls.Add(this.remoteLabel, 0, 2);
            this.layout.Controls.Add(this.remote, 1, 2);
            this.layout.Controls.Add(this.branchLabel, 0, 3);
            this.layout.Controls.Add(this.branch, 1, 3);
            this.layout.Controls.Add(this.connect, 1, 4);
            this.layout.Controls.Add(this.messageLabel, 0, 5);
            this.layout.Controls.Add(this.commitMessage, 1, 5);
            this.layout.Controls.Add(this.syncStatus, 0, 6);
            this.layout.SetColumnSpan(this.syncStatus, 2);
            this.layout.Controls.Add(this.actions, 0, 7);
            this.layout.SetColumnSpan(this.actions, 2);
            this.layout.Controls.Add(this.tabs, 0, 8);
            this.layout.SetColumnSpan(this.tabs, 2);
            this.layout.Controls.Add(this.status, 0, 9);
            this.layout.SetColumnSpan(this.status, 2);
            this.layout.Name = "layout";
            // documentLabel
            this.documentLabel.Text = "GitHub · sources VBA";
            this.documentLabel.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.documentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.documentLabel.AutoEllipsis = true;
            this.documentLabel.Name = "documentLabel";
            // help
            this.help.Text = "Les modifications du VBA deviennent des fichiers sources dans le dépôt. Aucun dossier à côté de la macro.\r\nLe premier pull remplace le VBA avec une sauvegarde restaurable.\r\nConnexion via Git Credential Manager ; identité de commit configurée dans Git.";
            this.help.Dock = System.Windows.Forms.DockStyle.Fill;
            this.help.Name = "help";
            // fields
            this.remoteLabel.Text = "Dépôt GitHub";
            this.remoteLabel.AutoSize = true;
            this.remoteLabel.Name = "remoteLabel";
            this.remote.Dock = System.Windows.Forms.DockStyle.Fill;
            this.remote.Name = "remote";
            this.remote.TabIndex = 0;
            this.toolTips.SetToolTip(this.remote, "URL HTTPS, par exemple https://github.com/organisation/macros.git. Ne collez aucun jeton.");
            this.branchLabel.Text = "Branche";
            this.branchLabel.AutoSize = true;
            this.branchLabel.Name = "branchLabel";
            this.branch.Text = "main";
            this.branch.Dock = System.Windows.Forms.DockStyle.Fill;
            this.branch.Name = "branch";
            this.branch.TabIndex = 1;
            this.toolTips.SetToolTip(this.branch, "Branche à synchroniser. Les push ne sont jamais forcés.");
            this.connect.Text = "Lier le dépôt";
            this.connect.AutoSize = true;
            this.connect.Name = "connect";
            this.connect.TabIndex = 2;
            this.connect.Click += new System.EventHandler(this.Connect_Click);
            this.toolTips.SetToolTip(this.connect, "Mémorise la liaison pour ce document sur cet ordinateur. Ne publie aucun code.");
            this.messageLabel.Text = "Message de commit";
            this.messageLabel.AutoSize = true;
            this.messageLabel.Name = "messageLabel";
            this.commitMessage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.commitMessage.Multiline = true;
            this.commitMessage.Name = "commitMessage";
            this.commitMessage.TabIndex = 3;
            // actions
            this.actions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actions.Name = "actions";
            this.actions.Controls.Add(this.compare);
            this.actions.Controls.Add(this.commit);
            this.actions.Controls.Add(this.fetch);
            this.actions.Controls.Add(this.push);
            this.actions.Controls.Add(this.pull);
            this.actions.Controls.Add(this.restore);
            this.compare.Text = "Comparer";
            this.compare.AutoSize = true;
            this.compare.Enabled = false;
            this.compare.Name = "compare";
            this.compare.Click += new System.EventHandler(this.Compare_Click);
            this.toolTips.SetToolTip(this.compare, "Compare le VBA vivant au dernier état synchronisé, sans accès réseau.");
            this.commit.Text = "Commit (tout)";
            this.commit.AutoSize = true;
            this.commit.Enabled = false;
            this.commit.Name = "commit";
            this.commit.Click += new System.EventHandler(this.Commit_Click);
            this.toolTips.SetToolTip(this.commit, "Exporte les sources et crée un commit local de tous les changements. Push les publie ensuite.");
            this.fetch.Text = "Fetch";
            this.fetch.AutoSize = true;
            this.fetch.Enabled = false;
            this.fetch.Name = "fetch";
            this.fetch.Click += new System.EventHandler(this.Fetch_Click);
            this.toolTips.SetToolTip(this.fetch, "Actualise les commits distants et les compteurs sans modifier le VBA.");
            this.push.Text = "Push";
            this.push.AutoSize = true;
            this.push.Enabled = false;
            this.push.Name = "push";
            this.push.Click += new System.EventHandler(this.Push_Click);
            this.toolTips.SetToolTip(this.push, "Publie les commits locaux sur la branche choisie. Ne publie pas les modifications non commitées.");
            this.pull.Text = "Pull et importer";
            this.pull.AutoSize = true;
            this.pull.Enabled = false;
            this.pull.Name = "pull";
            this.pull.Click += new System.EventHandler(this.Pull_Click);
            this.toolTips.SetToolTip(this.pull, "Télécharge et importe les sources. Refuse les modifications locales non synchronisées et les historiques divergents.");
            this.restore.Text = "Restaurer VBA";
            this.restore.AutoSize = true;
            this.restore.Enabled = false;
            this.restore.Name = "restore";
            this.restore.Click += new System.EventHandler(this.Restore_Click);
            this.toolTips.SetToolTip(this.restore, "Restaure la sauvegarde avant le dernier import, si le VBA n’a pas été modifié depuis. Ne réécrit pas GitHub.");
            // changes and status
            this.changes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.changes.HorizontalScrollbar = true;
            this.changes.IntegralHeight = false;
            this.changes.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.changes.Name = "changes";
            this.changes.SelectedIndexChanged += new System.EventHandler(this.Changes_SelectedIndexChanged);
            this.syncStatus.Text = "Branche non liée";
            this.syncStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.syncStatus.Name = "syncStatus";
            this.tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabs.Name = "tabs";
            this.tabs.Controls.Add(this.changesTab);
            this.tabs.Controls.Add(this.historyTab);
            this.changesTab.Text = "Modifications Git";
            this.changesTab.Name = "changesTab";
            this.changesTab.Controls.Add(this.changeSplit);
            this.historyTab.Text = "Historique";
            this.historyTab.Name = "historyTab";
            this.historyTab.Controls.Add(this.history);
            this.history.Dock = System.Windows.Forms.DockStyle.Fill;
            this.history.HorizontalScrollbar = true;
            this.history.Name = "history";
            this.changeSplit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.changeSplit.Size = new System.Drawing.Size(860, 260);
            this.changeSplit.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.changeSplit.SplitterDistance = 200;
            this.changeSplit.Name = "changeSplit";
            this.changeSplit.Panel1.Controls.Add(this.changes);
            this.changeSplit.Panel2.Controls.Add(this.diff);
            this.diff.Dock = System.Windows.Forms.DockStyle.Fill;
            this.diff.ReadOnly = true;
            this.diff.AllowUserToAddRows = false;
            this.diff.AllowUserToDeleteRows = false;
            this.diff.AllowUserToOrderColumns = false;
            this.diff.RowHeadersVisible = false;
            this.diff.BackgroundColor = System.Drawing.Color.White;
            this.diff.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.diff.Font = new System.Drawing.Font("Consolas", 9F);
            this.diff.Name = "diff";
            this.diff.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.beforeColumn, this.afterColumn });
            this.beforeColumn.Name = "beforeColumn";
            this.beforeColumn.HeaderText = "Dernier commit / import";
            this.beforeColumn.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.beforeColumn.MinimumWidth = 280;
            this.afterColumn.Name = "afterColumn";
            this.afterColumn.HeaderText = "VBA actuel";
            this.afterColumn.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.afterColumn.MinimumWidth = 280;
            this.status.Text = "Liez un dépôt GitHub existant pour commencer.";
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.Padding = new System.Windows.Forms.Padding(0, 12, 0, 0);
            this.status.Name = "status";
            // window
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            this.ClientSize = new System.Drawing.Size(960, 780);
            this.MinimumSize = new System.Drawing.Size(900, 700);
            this.Controls.Add(this.layout);
            this.Name = "GitWindow";
            this.Text = "GitHub · CodexVBA";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.ShowInTaskbar = false;
            this.layout.ResumeLayout(false);
            this.layout.PerformLayout();
            this.actions.ResumeLayout(false);
            this.actions.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
