namespace VBAi
{
    /// <summary>Designer-generated controls and layout for the Git workflow window.</summary>
    internal sealed partial class GitWindow
    {
        /// <summary>Root layout for document selection, tabs, operations, and status.</summary>
        private System.Windows.Forms.TableLayoutPanel layout;
        /// <summary>Label showing the active VBA document.</summary>
        private System.Windows.Forms.Label documentLabel;
        /// <summary>Tab control containing local Git workflows and GitHub views.</summary>
        private VBAi.ThemedTabControl tabs;
        /// <summary>Changes review tab.</summary>
        private System.Windows.Forms.TabPage changesTab;
        /// <summary>Commit history tab.</summary>
        private System.Windows.Forms.TabPage historyTab;
        /// <summary>Branch management tab.</summary>
        private System.Windows.Forms.TabPage branchesTab;
        /// <summary>Checkpoint management tab.</summary>
        private System.Windows.Forms.TabPage checkpointsTab;
        /// <summary>Merge conflict resolution tab.</summary>
        private System.Windows.Forms.TabPage conflictsTab;
        /// <summary>GitHub repository and pull-request tab.</summary>
        private System.Windows.Forms.TabPage githubTab;
        /// <summary>Repository import tab.</summary>
        private System.Windows.Forms.TabPage importTab;
        /// <summary>Embedded GitHub repository and pull-request pane.</summary>
        private VBAi.GitHubPane githubPane;
        /// <summary>Primary repository operation buttons.</summary>
        private System.Windows.Forms.FlowLayoutPanel actions;
        /// <summary>Compares local and remote content.</summary>
        private VBAi.ThemedButton compare;
        /// <summary>Fetches remote references.</summary>
        private VBAi.ThemedButton fetch;
        /// <summary>Pushes local commits.</summary>
        private VBAi.ThemedButton push;
        /// <summary>Pulls remote changes.</summary>
        private VBAi.ThemedButton pull;
        /// <summary>Restores a selected checkpoint or revision.</summary>
        private VBAi.ThemedButton restore;
        /// <summary>Previews importing a remote repository.</summary>
        private VBAi.ThemedButton previewImport;
        /// <summary>Remote synchronization state text.</summary>
        private System.Windows.Forms.Label syncStatus;
        /// <summary>General operation feedback.</summary>
        private System.Windows.Forms.Label status;
        /// <summary>Layout for the active operation status and progress.</summary>
        private System.Windows.Forms.TableLayoutPanel operationStatus;
        /// <summary>Progress indicator for repository operations.</summary>
        private System.Windows.Forms.ProgressBar operationProgress;
        /// <summary>Cancels the current repository operation.</summary>
        private VBAi.ThemedButton cancelOperation;
        /// <summary>Tooltips associated with repository actions.</summary>
        private System.Windows.Forms.ToolTip toolTips;
        /// <summary>Container that owns Designer components.</summary>
        private System.ComponentModel.IContainer components;
        /// <summary>GitHub connection tab.</summary>
        private System.Windows.Forms.TabPage connectionTab;
        /// <summary>Embedded connection and account settings view.</summary>
        private VBAi.GitConnectionView gitConnectionView;
        /// <summary>Embedded working-tree changes view.</summary>
        private VBAi.GitChangesView gitChangesView;
        /// <summary>Embedded commit history view.</summary>
        private VBAi.GitHistoryView gitHistoryView;
        /// <summary>Embedded branch management view.</summary>
        private VBAi.GitBranchesView gitBranchesView;
        /// <summary>Embedded checkpoint management view.</summary>
        private VBAi.GitCheckpointsView gitCheckpointsView;
        /// <summary>Embedded merge conflict view.</summary>
        private VBAi.GitConflictsView gitConflictsView;
        /// <summary>Embedded repository import view.</summary>
        private VBAi.GitImportView gitImportView;
        /// <summary>Creates and arranges Git workflow tabs and their child views.</summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.layout = new System.Windows.Forms.TableLayoutPanel();
            this.documentLabel = new System.Windows.Forms.Label();
            this.fetch = new VBAi.ThemedButton();
            this.syncStatus = new System.Windows.Forms.Label();
            this.tabs = new VBAi.ThemedTabControl();
            this.changesTab = new System.Windows.Forms.TabPage();
            this.historyTab = new System.Windows.Forms.TabPage();
            this.compare = new VBAi.ThemedButton();
            this.push = new VBAi.ThemedButton();
            this.pull = new VBAi.ThemedButton();
            this.restore = new VBAi.ThemedButton();
            this.actions = new System.Windows.Forms.FlowLayoutPanel();
            this.status = new System.Windows.Forms.Label();
            this.toolTips = new System.Windows.Forms.ToolTip(this.components);
            this.branchesTab = new System.Windows.Forms.TabPage();
            this.checkpointsTab = new System.Windows.Forms.TabPage();
            this.conflictsTab = new System.Windows.Forms.TabPage();
            this.githubTab = new System.Windows.Forms.TabPage();
            this.githubPane = new VBAi.GitHubPane();
            this.cancelOperation = new VBAi.ThemedButton();
            this.operationProgress = new System.Windows.Forms.ProgressBar();
            this.operationStatus = new System.Windows.Forms.TableLayoutPanel();
            this.importTab = new System.Windows.Forms.TabPage();
            this.previewImport = new VBAi.ThemedButton();
            this.connectionTab = new System.Windows.Forms.TabPage();
            this.gitConnectionView = new VBAi.GitConnectionView();
            this.gitChangesView = new VBAi.GitChangesView();
            this.gitHistoryView = new VBAi.GitHistoryView();
            this.gitBranchesView = new VBAi.GitBranchesView();
            this.gitCheckpointsView = new VBAi.GitCheckpointsView();
            this.gitConflictsView = new VBAi.GitConflictsView();
            this.gitImportView = new VBAi.GitImportView();
            this.layout.SuspendLayout();
            this.tabs.SuspendLayout();
            this.changesTab.SuspendLayout();
            this.historyTab.SuspendLayout();
            this.branchesTab.SuspendLayout();
            this.checkpointsTab.SuspendLayout();
            this.conflictsTab.SuspendLayout();
            this.githubTab.SuspendLayout();
            this.importTab.SuspendLayout();
            this.githubPane.SuspendLayout();
            this.actions.SuspendLayout();
            this.operationStatus.SuspendLayout();
            this.connectionTab.SuspendLayout();
            this.gitConnectionView.SuspendLayout();
            this.gitChangesView.SuspendLayout();
            this.gitHistoryView.SuspendLayout();
            this.gitBranchesView.SuspendLayout();
            this.gitCheckpointsView.SuspendLayout();
            this.gitConflictsView.SuspendLayout();
            this.gitImportView.SuspendLayout();
            this.SuspendLayout();
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(960, 780);
            this.MinimumSize = new System.Drawing.Size(700, 580);
            this.documentLabel.Text = "GitHub · VBA sources";
            this.documentLabel.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.documentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.documentLabel.AutoEllipsis = true;
            this.documentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.documentLabel.Name = "documentLabel";
            this.actions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actions.AutoSize = true;
            this.actions.Name = "actions";
            this.compare.Text = "Compare";
            this.compare.AutoSize = true;
            this.compare.Enabled = false;
            this.compare.Name = "compare";
            this.compare.Click += new System.EventHandler(this.Compare_Click);
            this.toolTips.SetToolTip(this.compare, "Compare live VBA with the last synchronized state without network access.");
            this.fetch.Text = "Fetch";
            this.fetch.AutoSize = true;
            this.fetch.Enabled = false;
            this.fetch.Name = "fetch";
            this.fetch.Click += new System.EventHandler(this.Fetch_Click);
            this.toolTips.SetToolTip(this.fetch, "Refresh remote commits and counts without changing VBA.");
            this.push.Text = "Push";
            this.push.AutoSize = true;
            this.push.Enabled = false;
            this.push.Name = "push";
            this.push.Click += new System.EventHandler(this.Push_Click);
            this.toolTips.SetToolTip(this.push, "Publish local commits on the chosen branch. Does not publish uncommitted changes.");
            this.pull.Text = "Pull and import";
            this.pull.AutoSize = true;
            this.pull.Enabled = false;
            this.pull.Name = "pull";
            this.pull.Click += new System.EventHandler(this.Pull_Click);
            this.toolTips.SetToolTip(this.pull, "Download and import sources. Refuses unsynchronized local changes and divergent histories.");
            this.restore.Text = "Restore VBA";
            this.restore.AutoSize = true;
            this.restore.Enabled = false;
            this.restore.Name = "restore";
            this.restore.Click += new System.EventHandler(this.Restore_Click);
            this.toolTips.SetToolTip(this.restore, "Restore the backup made before the last import if VBA has not changed since. Does not rewrite GitHub.");
            this.syncStatus.Text = "Branch not linked";
            this.syncStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.syncStatus.Name = "syncStatus";
            this.tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabs.Name = "tabs";
            this.tabs.ItemSize = new System.Drawing.Size(0, 36);
            this.tabs.Padding = new System.Drawing.Point(12, 6);
            this.branchesTab.Text = "Branches";
            this.branchesTab.Name = "branchesTab";
            this.branchesTab.Enabled = false;
            this.checkpointsTab.Text = "Checkpoints";
            this.checkpointsTab.Name = "checkpointsTab";
            this.checkpointsTab.Enabled = false;
            this.conflictsTab.Text = "Conflicts";
            this.conflictsTab.Name = "conflictsTab";
            this.conflictsTab.Enabled = false;
            this.changesTab.Text = "Git changes";
            this.changesTab.Name = "changesTab";
            this.historyTab.Text = "History";
            this.historyTab.Name = "historyTab";
            this.status.Text = "Link an existing GitHub repository to get started.";
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.Padding = new System.Windows.Forms.Padding(0, 6, 8, 0);
            this.status.Name = "status";
            this.githubTab.Name = "githubTab";
            this.githubPane.Name = "githubPane";
            this.cancelOperation.Name = "cancelOperation";
            this.operationProgress.Name = "operationProgress";
            this.importTab.Name = "importTab";
            this.githubTab.Text = "GitHub";
            this.githubPane.Dock = System.Windows.Forms.DockStyle.Fill;
            this.importTab.Text = "Import summary";
            this.cancelOperation.Text = "Cancel";
            this.cancelOperation.Enabled = false;
            this.cancelOperation.AutoSize = true;
            this.cancelOperation.Click += new System.EventHandler(this.CancelOperation_Click);
            this.operationProgress.Style = System.Windows.Forms.ProgressBarStyle.Marquee;
            this.operationProgress.Visible = false;
            this.operationStatus.Name = "operationStatus";
            this.operationStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.operationStatus.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.operationStatus.ColumnCount = 2;
            this.operationStatus.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.operationStatus.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.operationStatus.RowCount = 2;
            this.operationStatus.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.operationStatus.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 3F));
            this.operationStatus.SetColumnSpan(this.operationProgress, 2);
            this.operationProgress.Dock = System.Windows.Forms.DockStyle.Fill;
            this.operationProgress.Margin = new System.Windows.Forms.Padding(0);
            this.cancelOperation.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.cancelOperation.Visible = false;
            this.previewImport.Name = "previewImport";
            this.previewImport.Text = "Preview import";
            this.previewImport.AutoSize = true;
            this.previewImport.Click += new System.EventHandler(this.PreviewImport_Click);
            this.push.Margin = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.pull.Margin = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.connectionTab.Name = "connectionTab";
            this.connectionTab.Text = "GitHub repository";
            this.gitConnectionView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitChangesView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitHistoryView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitBranchesView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitCheckpointsView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitConflictsView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitImportView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.connectionTab.Controls.Add(this.gitConnectionView);
            this.tabs.Controls.Add(this.connectionTab);
            this.changesTab.Controls.Add(this.gitChangesView);
            this.tabs.Controls.Add(this.changesTab);
            this.historyTab.Controls.Add(this.gitHistoryView);
            this.tabs.Controls.Add(this.historyTab);
            this.branchesTab.Controls.Add(this.gitBranchesView);
            this.tabs.Controls.Add(this.branchesTab);
            this.checkpointsTab.Controls.Add(this.gitCheckpointsView);
            this.tabs.Controls.Add(this.checkpointsTab);
            this.conflictsTab.Controls.Add(this.gitConflictsView);
            this.tabs.Controls.Add(this.conflictsTab);
            this.importTab.Controls.Add(this.gitImportView);
            this.tabs.Controls.Add(this.importTab);
            this.githubTab.Controls.Add(this.githubPane);
            this.tabs.Controls.Add(this.githubTab);
            this.layout.ColumnCount = 2;
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.layout.RowCount = 5;
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 26F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 0F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            this.layout.Controls.Add(this.documentLabel, 0, 0);
            this.layout.Controls.Add(this.syncStatus, 0, 1);
            this.layout.Controls.Add(this.actions, 1, 0);
            this.actions.WrapContents = false;
            this.actions.Margin = new System.Windows.Forms.Padding(0);
            this.layout.Controls.Add(this.tabs, 0, 3);
            this.layout.Controls.Add(this.operationStatus, 0, 4);
            this.layout.SetColumnSpan(this.syncStatus, 2);
            this.layout.SetColumnSpan(this.tabs, 2);
            this.layout.SetColumnSpan(this.operationStatus, 2);
            this.connectionTab.Padding = new System.Windows.Forms.Padding(6);
            this.changesTab.Padding = new System.Windows.Forms.Padding(6);
            this.historyTab.Padding = new System.Windows.Forms.Padding(6);
            this.branchesTab.Padding = new System.Windows.Forms.Padding(6);
            this.checkpointsTab.Padding = new System.Windows.Forms.Padding(6);
            this.conflictsTab.Padding = new System.Windows.Forms.Padding(6);
            this.importTab.Padding = new System.Windows.Forms.Padding(6);
            this.githubTab.Padding = new System.Windows.Forms.Padding(6);
            this.actions.Controls.Add(this.compare);
            this.actions.Controls.Add(this.fetch);
            this.actions.Controls.Add(this.push);
            this.actions.Controls.Add(this.previewImport);
            this.actions.Controls.Add(this.pull);
            this.actions.Controls.Add(this.restore);
            this.operationStatus.Controls.Add(this.status, 0, 0);
            this.operationStatus.Controls.Add(this.cancelOperation, 1, 0);
            this.operationStatus.Controls.Add(this.operationProgress, 0, 1);
            this.operationStatus.SetColumnSpan(this.operationProgress, 2);
            this.layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layout.Padding = new System.Windows.Forms.Padding(12);
            this.Controls.Add(this.layout);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "GitWindow";
            this.Text = "GitHub · VBAi";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.ShowInTaskbar = false;
            this.layout.Name = "layout";
            this.layout.Location = new System.Drawing.Point(0, 0);
            this.layout.Size = new System.Drawing.Size(960, 780);
            this.layout.TabIndex = 0;
            this.documentLabel.Location = new System.Drawing.Point(23, 20);
            this.documentLabel.Size = new System.Drawing.Size(914, 40);
            this.documentLabel.TabIndex = 0;
            this.tabs.Location = new System.Drawing.Point(23, 131);
            this.tabs.Size = new System.Drawing.Size(914, 562);
            this.tabs.TabIndex = 3;
            this.changesTab.Location = new System.Drawing.Point(0, 0);
            this.changesTab.Size = new System.Drawing.Size(200, 100);
            this.changesTab.TabIndex = 1;
            this.historyTab.Location = new System.Drawing.Point(0, 0);
            this.historyTab.Size = new System.Drawing.Size(200, 100);
            this.historyTab.TabIndex = 2;
            this.branchesTab.Location = new System.Drawing.Point(0, 0);
            this.branchesTab.Size = new System.Drawing.Size(200, 100);
            this.branchesTab.TabIndex = 3;
            this.checkpointsTab.Location = new System.Drawing.Point(0, 0);
            this.checkpointsTab.Size = new System.Drawing.Size(200, 100);
            this.checkpointsTab.TabIndex = 4;
            this.conflictsTab.Location = new System.Drawing.Point(0, 0);
            this.conflictsTab.Size = new System.Drawing.Size(200, 100);
            this.conflictsTab.TabIndex = 5;
            this.githubTab.Location = new System.Drawing.Point(0, 0);
            this.githubTab.Size = new System.Drawing.Size(200, 100);
            this.githubTab.TabIndex = 7;
            this.importTab.Location = new System.Drawing.Point(0, 0);
            this.importTab.Size = new System.Drawing.Size(200, 100);
            this.importTab.TabIndex = 6;
            this.githubPane.Location = new System.Drawing.Point(0, 0);
            this.githubPane.Size = new System.Drawing.Size(200, 100);
            this.githubPane.TabIndex = 0;
            this.actions.Location = new System.Drawing.Point(23, 91);
            this.actions.Size = new System.Drawing.Size(914, 34);
            this.actions.TabIndex = 2;
            this.compare.Location = new System.Drawing.Point(3, 3);
            this.compare.Size = new System.Drawing.Size(75, 28);
            this.compare.TabIndex = 0;
            this.fetch.Location = new System.Drawing.Point(84, 3);
            this.fetch.Size = new System.Drawing.Size(75, 28);
            this.fetch.TabIndex = 1;
            this.push.Location = new System.Drawing.Point(165, 3);
            this.push.Size = new System.Drawing.Size(75, 28);
            this.push.TabIndex = 2;
            this.pull.Location = new System.Drawing.Point(361, 3);
            this.pull.Size = new System.Drawing.Size(98, 28);
            this.pull.TabIndex = 4;
            this.restore.Location = new System.Drawing.Point(477, 3);
            this.restore.Size = new System.Drawing.Size(82, 28);
            this.restore.TabIndex = 5;
            this.previewImport.Location = new System.Drawing.Point(258, 3);
            this.previewImport.Size = new System.Drawing.Size(97, 28);
            this.previewImport.TabIndex = 3;
            this.syncStatus.Location = new System.Drawing.Point(23, 60);
            this.syncStatus.Size = new System.Drawing.Size(914, 28);
            this.syncStatus.TabIndex = 1;
            this.status.Location = new System.Drawing.Point(3, 0);
            this.status.Size = new System.Drawing.Size(804, 55);
            this.status.TabIndex = 0;
            this.operationStatus.Location = new System.Drawing.Point(20, 702);
            this.operationStatus.Size = new System.Drawing.Size(920, 58);
            this.operationStatus.TabIndex = 4;
            this.operationProgress.Location = new System.Drawing.Point(0, 0);
            this.operationProgress.Size = new System.Drawing.Size(100, 23);
            this.operationProgress.TabIndex = 2;
            this.cancelOperation.Location = new System.Drawing.Point(0, 0);
            this.cancelOperation.Size = new System.Drawing.Size(75, 23);
            this.cancelOperation.TabIndex = 1;
            this.connectionTab.Location = new System.Drawing.Point(0, 0);
            this.connectionTab.Size = new System.Drawing.Size(200, 100);
            this.connectionTab.TabIndex = 0;
            this.gitConnectionView.Name = "gitConnectionView";
            this.gitConnectionView.Location = new System.Drawing.Point(0, 0);
            this.gitConnectionView.Size = new System.Drawing.Size(200, 100);
            this.gitConnectionView.TabIndex = 0;
            this.gitChangesView.Name = "gitChangesView";
            this.gitChangesView.Location = new System.Drawing.Point(0, 0);
            this.gitChangesView.Size = new System.Drawing.Size(200, 100);
            this.gitChangesView.TabIndex = 0;
            this.gitHistoryView.Name = "gitHistoryView";
            this.gitHistoryView.Location = new System.Drawing.Point(0, 0);
            this.gitHistoryView.Size = new System.Drawing.Size(200, 100);
            this.gitHistoryView.TabIndex = 0;
            this.gitBranchesView.Name = "gitBranchesView";
            this.gitBranchesView.Location = new System.Drawing.Point(0, 0);
            this.gitBranchesView.Size = new System.Drawing.Size(200, 100);
            this.gitBranchesView.TabIndex = 0;
            this.gitCheckpointsView.Name = "gitCheckpointsView";
            this.gitCheckpointsView.Location = new System.Drawing.Point(0, 0);
            this.gitCheckpointsView.Size = new System.Drawing.Size(200, 100);
            this.gitCheckpointsView.TabIndex = 0;
            this.gitConflictsView.Name = "gitConflictsView";
            this.gitConflictsView.Location = new System.Drawing.Point(0, 0);
            this.gitConflictsView.Size = new System.Drawing.Size(200, 100);
            this.gitConflictsView.TabIndex = 0;
            this.gitImportView.Name = "gitImportView";
            this.gitImportView.Location = new System.Drawing.Point(0, 0);
            this.gitImportView.Size = new System.Drawing.Size(200, 100);
            this.gitImportView.TabIndex = 0;
            this.layout.ResumeLayout(false);
            this.layout.PerformLayout();
            this.tabs.ResumeLayout(false);
            this.tabs.PerformLayout();
            this.changesTab.ResumeLayout(false);
            this.changesTab.PerformLayout();
            this.historyTab.ResumeLayout(false);
            this.historyTab.PerformLayout();
            this.branchesTab.ResumeLayout(false);
            this.branchesTab.PerformLayout();
            this.checkpointsTab.ResumeLayout(false);
            this.checkpointsTab.PerformLayout();
            this.conflictsTab.ResumeLayout(false);
            this.conflictsTab.PerformLayout();
            this.githubTab.ResumeLayout(false);
            this.githubTab.PerformLayout();
            this.importTab.ResumeLayout(false);
            this.importTab.PerformLayout();
            this.githubPane.ResumeLayout(false);
            this.githubPane.PerformLayout();
            this.actions.ResumeLayout(false);
            this.actions.PerformLayout();
            this.operationStatus.ResumeLayout(false);
            this.operationStatus.PerformLayout();
            this.connectionTab.ResumeLayout(false);
            this.connectionTab.PerformLayout();
            this.gitConnectionView.ResumeLayout(false);
            this.gitConnectionView.PerformLayout();
            this.gitChangesView.ResumeLayout(false);
            this.gitChangesView.PerformLayout();
            this.gitHistoryView.ResumeLayout(false);
            this.gitHistoryView.PerformLayout();
            this.gitBranchesView.ResumeLayout(false);
            this.gitBranchesView.PerformLayout();
            this.gitCheckpointsView.ResumeLayout(false);
            this.gitCheckpointsView.PerformLayout();
            this.gitConflictsView.ResumeLayout(false);
            this.gitConflictsView.PerformLayout();
            this.gitImportView.ResumeLayout(false);
            this.gitImportView.PerformLayout();
            this.fetch.Symbol = VBAi.UiSymbol.Refresh;
            this.fetch.IconOnly = true;
            this.fetch.AutoSize = false;
            this.fetch.MinimumSize = System.Drawing.Size.Empty;
            this.fetch.Size = new System.Drawing.Size(32, 30);
            this.compare.Symbol = VBAi.UiSymbol.Inspect;
            this.compare.IconOnly = true;
            this.compare.AutoSize = false;
            this.compare.MinimumSize = System.Drawing.Size.Empty;
            this.compare.Size = new System.Drawing.Size(32, 30);
            this.push.Symbol = VBAi.UiSymbol.Upload;
            this.push.IconOnly = true;
            this.push.AutoSize = false;
            this.push.MinimumSize = System.Drawing.Size.Empty;
            this.push.Size = new System.Drawing.Size(32, 30);
            this.pull.Symbol = VBAi.UiSymbol.Download;
            this.pull.IconOnly = true;
            this.pull.AutoSize = false;
            this.pull.MinimumSize = System.Drawing.Size.Empty;
            this.pull.Size = new System.Drawing.Size(32, 30);
            this.restore.Symbol = VBAi.UiSymbol.Undo;
            this.restore.IconOnly = true;
            this.restore.AutoSize = false;
            this.restore.MinimumSize = System.Drawing.Size.Empty;
            this.restore.Size = new System.Drawing.Size(32, 30);
            this.cancelOperation.Symbol = VBAi.UiSymbol.Stop;
            this.cancelOperation.IconOnly = true;
            this.cancelOperation.AutoSize = false;
            this.cancelOperation.MinimumSize = System.Drawing.Size.Empty;
            this.cancelOperation.Size = new System.Drawing.Size(32, 30);
            this.previewImport.Symbol = VBAi.UiSymbol.Inspect;
            this.previewImport.IconOnly = true;
            this.previewImport.AutoSize = false;
            this.previewImport.MinimumSize = System.Drawing.Size.Empty;
            this.previewImport.Size = new System.Drawing.Size(32, 30);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
