namespace CodexVBE
{
    public sealed partial class GitHubPane
    {
        private CodexVBE.ThemedTabControl pages;
        private System.Windows.Forms.TabPage repositoriesPage;
        private System.Windows.Forms.TabPage pullsPage;
        private System.Windows.Forms.Label status;
        private CodexVBE.ThemedButton cancel;
        private System.Windows.Forms.FlowLayoutPanel footer;
        private System.Windows.Forms.ToolTip tips;
        private System.ComponentModel.IContainer components;
        private CodexVBE.GitHubRepositoriesView gitHubRepositoriesView;
        private CodexVBE.GitHubPullRequestsView gitHubPullRequestsView;
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.gitHubPullRequestsView = new CodexVBE.GitHubPullRequestsView();
            this.gitHubRepositoriesView = new CodexVBE.GitHubRepositoriesView();
            this.pages = new CodexVBE.ThemedTabControl();
            this.repositoriesPage = new System.Windows.Forms.TabPage();
            this.pullsPage = new System.Windows.Forms.TabPage();
            this.status = new System.Windows.Forms.Label();
            this.cancel = new CodexVBE.ThemedButton();
            this.footer = new System.Windows.Forms.FlowLayoutPanel();
            this.pages.SuspendLayout();
            this.repositoriesPage.SuspendLayout();
            this.pullsPage.SuspendLayout();
            this.footer.SuspendLayout();
            this.gitHubRepositoriesView.SuspendLayout();
            this.gitHubPullRequestsView.SuspendLayout();
            this.SuspendLayout();
            this.tips = new System.Windows.Forms.ToolTip(this.components);
            this.pages.Name = "pages";
            this.repositoriesPage.Name = "repositoriesPage";
            this.pullsPage.Name = "pullsPage";
            this.status.Name = "status";
            this.cancel.Name = "cancel";
            this.footer.Name = "footer";
            this.pages.Dock = System.Windows.Forms.DockStyle.Fill;
            this.footer.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.footer.AutoSize = true;
            this.status.AutoSize = true;
            this.status.MaximumSize = new System.Drawing.Size(700, 0);
            this.footer.Controls.Add(this.status);
            this.cancel.Text = "Cancel";
            this.cancel.AutoSize = true;
            this.cancel.Click += new System.EventHandler(this.Cancel_Click);
            this.footer.Controls.Add(this.cancel);
            this.tips.SetToolTip(this.cancel, "Cancel");
            this.cancel.Enabled = false;
            this.repositoriesPage.Text = "Repositories";
            this.pages.Controls.Add(this.repositoriesPage);
            this.pullsPage.Text = "Pull requests";
            this.pages.Controls.Add(this.pullsPage);
            this.gitHubRepositoriesView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.repositoriesPage.Controls.Add(this.gitHubRepositoriesView);
            this.gitHubPullRequestsView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pullsPage.Controls.Add(this.gitHubPullRequestsView);
            this.Controls.Add(this.pages);
            this.Controls.Add(this.footer);
            this.Name = "GitHubPane";
            this.Size = new System.Drawing.Size(860, 500);
            this.pages.Location = new System.Drawing.Point(0, 0);
            this.pages.Size = new System.Drawing.Size(860, 470);
            this.pages.TabIndex = 0;
            this.repositoriesPage.Location = new System.Drawing.Point(0, 0);
            this.repositoriesPage.Size = new System.Drawing.Size(200, 100);
            this.repositoriesPage.TabIndex = 0;
            this.pullsPage.Location = new System.Drawing.Point(0, 0);
            this.pullsPage.Size = new System.Drawing.Size(200, 100);
            this.pullsPage.TabIndex = 1;
            this.status.Location = new System.Drawing.Point(3, 0);
            this.status.Size = new System.Drawing.Size(0, 16);
            this.status.TabIndex = 0;
            this.cancel.Location = new System.Drawing.Point(9, 3);
            this.cancel.Size = new System.Drawing.Size(75, 24);
            this.cancel.TabIndex = 1;
            this.footer.Location = new System.Drawing.Point(0, 470);
            this.footer.Size = new System.Drawing.Size(860, 30);
            this.footer.TabIndex = 1;
            this.gitHubRepositoriesView.Name = "gitHubRepositoriesView";
            this.gitHubRepositoriesView.Location = new System.Drawing.Point(0, 0);
            this.gitHubRepositoriesView.Size = new System.Drawing.Size(200, 100);
            this.gitHubRepositoriesView.TabIndex = 0;
            this.gitHubPullRequestsView.Name = "gitHubPullRequestsView";
            this.gitHubPullRequestsView.Location = new System.Drawing.Point(0, 0);
            this.gitHubPullRequestsView.Size = new System.Drawing.Size(200, 100);
            this.gitHubPullRequestsView.TabIndex = 0;
            this.pages.ResumeLayout(false);
            this.pages.PerformLayout();
            this.repositoriesPage.ResumeLayout(false);
            this.repositoriesPage.PerformLayout();
            this.pullsPage.ResumeLayout(false);
            this.pullsPage.PerformLayout();
            this.footer.ResumeLayout(false);
            this.footer.PerformLayout();
            this.gitHubRepositoriesView.ResumeLayout(false);
            this.gitHubRepositoriesView.PerformLayout();
            this.gitHubPullRequestsView.ResumeLayout(false);
            this.gitHubPullRequestsView.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
