namespace CodexVBE
{
    internal sealed partial class GitWindow
    {
        private System.Windows.Forms.Label remoteLabel;
        private System.Windows.Forms.Label branchLabel;
        private System.Windows.Forms.Label help;
        private System.Windows.Forms.TextBox remote;
        private System.Windows.Forms.TextBox branch;
        private System.Windows.Forms.Button connect;
        private System.Windows.Forms.Label messageLabel;
        private System.Windows.Forms.TextBox commitMessage;
        private System.Windows.Forms.Button commit;
        private System.Windows.Forms.SplitContainer changeSplit;
        private CodexVBE.CodeDiffView diff;
        private System.Windows.Forms.CheckedListBox changes;
        private System.Windows.Forms.FlowLayoutPanel reviewActions;
        private System.Windows.Forms.Button openModule;
        private System.Windows.Forms.Button restoreModule;
        private System.Windows.Forms.ListBox history;
        private System.Windows.Forms.TextBox historyDetails;
        private System.Windows.Forms.Button historyCompare;
        private System.Windows.Forms.FlowLayoutPanel branchActions;
        private System.Windows.Forms.ListBox branchList;
        private System.Windows.Forms.ComboBox branchName;
        private System.Windows.Forms.Button branchRemote;
        private System.Windows.Forms.Button branchCreate;
        private System.Windows.Forms.Button branchTrack;
        private System.Windows.Forms.Button branchSwitch;
        private System.Windows.Forms.Button mergeBegin;
        private System.Windows.Forms.FlowLayoutPanel checkpointActions;
        private System.Windows.Forms.ListBox checkpointList;
        private System.Windows.Forms.TextBox checkpointName;
        private System.Windows.Forms.Button checkpointCreate;
        private System.Windows.Forms.Button checkpointRestore;
        private System.Windows.Forms.FlowLayoutPanel conflictActions;
        private System.Windows.Forms.ListBox conflictList;
        private System.Windows.Forms.TextBox resolutionText;
        private System.Windows.Forms.Button mergeOurs;
        private System.Windows.Forms.Button mergeTheirs;
        private System.Windows.Forms.Button mergeText;
        private System.Windows.Forms.Button mergeComplete;
        private System.Windows.Forms.Button mergeAbort;
        private System.Windows.Forms.DataGridView conflictDiff;
        private System.Windows.Forms.DataGridViewTextBoxColumn conflictOurs;
        private System.Windows.Forms.DataGridViewTextBoxColumn conflictTheirs;
        private System.Windows.Forms.TextBox baseContent;
        private System.Windows.Forms.TableLayoutPanel conflictLayout;
        private System.Windows.Forms.Label ancestorLabel;
        private System.Windows.Forms.Label resultLabel;
        private System.Windows.Forms.TextBox importSummary;
        private void BindViews()
        {
            remoteLabel = gitConnectionView.remoteLabel;
            branchLabel = gitConnectionView.branchLabel;
            help = gitConnectionView.help;
            remote = gitConnectionView.remote;
            branch = gitConnectionView.branch;
            connect = gitConnectionView.connect;
            messageLabel = gitChangesView.messageLabel;
            commitMessage = gitChangesView.commitMessage;
            commit = gitChangesView.commit;
            changeSplit = gitChangesView.changeSplit;
            diff = gitChangesView.diff;
            changes = gitChangesView.changes;
            reviewActions = gitChangesView.reviewActions;
            openModule = gitChangesView.openModule;
            restoreModule = gitChangesView.restoreModule;
            history = gitHistoryView.history;
            historyDetails = gitHistoryView.historyDetails;
            historyCompare = gitHistoryView.historyCompare;
            branchActions = gitBranchesView.branchActions;
            branchList = gitBranchesView.branchList;
            branchName = gitBranchesView.branchName;
            branchRemote = gitBranchesView.branchRemote;
            branchCreate = gitBranchesView.branchCreate;
            branchTrack = gitBranchesView.branchTrack;
            branchSwitch = gitBranchesView.branchSwitch;
            mergeBegin = gitBranchesView.mergeBegin;
            checkpointActions = gitCheckpointsView.checkpointActions;
            checkpointList = gitCheckpointsView.checkpointList;
            checkpointName = gitCheckpointsView.checkpointName;
            checkpointCreate = gitCheckpointsView.checkpointCreate;
            checkpointRestore = gitCheckpointsView.checkpointRestore;
            conflictActions = gitConflictsView.conflictActions;
            conflictList = gitConflictsView.conflictList;
            resolutionText = gitConflictsView.resolutionText;
            mergeOurs = gitConflictsView.mergeOurs;
            mergeTheirs = gitConflictsView.mergeTheirs;
            mergeText = gitConflictsView.mergeText;
            mergeComplete = gitConflictsView.mergeComplete;
            mergeAbort = gitConflictsView.mergeAbort;
            conflictDiff = gitConflictsView.conflictDiff;
            conflictOurs = gitConflictsView.conflictOurs;
            conflictTheirs = gitConflictsView.conflictTheirs;
            baseContent = gitConflictsView.baseContent;
            conflictLayout = gitConflictsView.conflictLayout;
            ancestorLabel = gitConflictsView.ancestorLabel;
            resultLabel = gitConflictsView.resultLabel;
            importSummary = gitImportView.importSummary;
            this.connect.Click += new System.EventHandler(this.Connect_Click);
            this.commit.Click += new System.EventHandler(this.Commit_Click);
            this.changes.SelectedIndexChanged += new System.EventHandler(this.Changes_SelectedIndexChanged);
            this.branchCreate.Click += new System.EventHandler(this.BranchCreate_Click);
            this.branchRemote.Click += new System.EventHandler(this.RemoteBranches_Click);
            this.branchTrack.Click += new System.EventHandler(this.BranchTrack_Click);
            this.branchSwitch.Click += new System.EventHandler(this.BranchSwitch_Click);
            this.mergeBegin.Click += new System.EventHandler(this.MergeBegin_Click);
            this.checkpointCreate.Click += new System.EventHandler(this.CheckpointCreate_Click);
            this.checkpointRestore.Click += new System.EventHandler(this.CheckpointRestore_Click);
            this.conflictList.SelectedIndexChanged += new System.EventHandler(this.ConflictList_SelectedIndexChanged);
            this.mergeOurs.Click += new System.EventHandler(this.MergeOurs_Click);
            this.mergeTheirs.Click += new System.EventHandler(this.MergeTheirs_Click);
            this.mergeText.Click += new System.EventHandler(this.MergeText_Click);
            this.mergeComplete.Click += new System.EventHandler(this.MergeComplete_Click);
            this.mergeAbort.Click += new System.EventHandler(this.MergeAbort_Click);
            this.openModule.Click += new System.EventHandler(this.OpenModule_Click);
            this.restoreModule.Click += new System.EventHandler(this.RestoreModule_Click);
            this.history.SelectedIndexChanged += new System.EventHandler(this.HistoryChanged);
            this.checkpointList.SelectedIndexChanged += new System.EventHandler(this.CheckpointChanged);
            this.historyCompare.Click += new System.EventHandler(this.HistoryChanged);
        }
    }
}
