namespace CodexVBE
{
    internal sealed partial class GitWindow
    {
        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.Label documentLabel;
        private System.Windows.Forms.TabControl tabs;
        private System.Windows.Forms.TabPage changesTab;
        private System.Windows.Forms.TabPage historyTab;
        private System.Windows.Forms.TabPage branchesTab;
        private System.Windows.Forms.TabPage checkpointsTab;
        private System.Windows.Forms.TabPage conflictsTab;
        private System.Windows.Forms.TabPage githubTab;
        private System.Windows.Forms.TabPage importTab;
        private CodexVBE.GitHubPane githubPane;
        private System.Windows.Forms.FlowLayoutPanel actions;
        private System.Windows.Forms.Button compare;
        private System.Windows.Forms.Button fetch;
        private System.Windows.Forms.Button push;
        private System.Windows.Forms.Button pull;
        private System.Windows.Forms.Button restore;
        private System.Windows.Forms.Button previewImport;
        private System.Windows.Forms.Label syncStatus;
        private System.Windows.Forms.Label status;
        private System.Windows.Forms.TableLayoutPanel operationStatus;
        private System.Windows.Forms.ProgressBar operationProgress;
        private System.Windows.Forms.Button cancelOperation;
        private System.Windows.Forms.ToolTip toolTips;
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.TabPage connectionTab;
        private CodexVBE.GitConnectionView gitConnectionView;
        private CodexVBE.GitChangesView gitChangesView;
        private CodexVBE.GitHistoryView gitHistoryView;
        private CodexVBE.GitBranchesView gitBranchesView;
        private CodexVBE.GitCheckpointsView gitCheckpointsView;
        private CodexVBE.GitConflictsView gitConflictsView;
        private CodexVBE.GitImportView gitImportView;
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.layout = new System.Windows.Forms.TableLayoutPanel();
            this.documentLabel = new System.Windows.Forms.Label();
            this.fetch = new CodexVBE.ThemedButton();
            this.syncStatus = new System.Windows.Forms.Label();
            this.tabs = new CodexVBE.ThemedTabControl();
            this.changesTab = new System.Windows.Forms.TabPage();
            this.historyTab = new System.Windows.Forms.TabPage();
            this.compare = new CodexVBE.ThemedButton();
            this.push = new CodexVBE.ThemedButton();
            this.pull = new CodexVBE.ThemedButton();
            this.restore = new CodexVBE.ThemedButton();
            this.actions = new System.Windows.Forms.FlowLayoutPanel();
            this.status = new System.Windows.Forms.Label();
            this.toolTips = new System.Windows.Forms.ToolTip(this.components);
            this.branchesTab = new System.Windows.Forms.TabPage();
            this.checkpointsTab = new System.Windows.Forms.TabPage();
            this.conflictsTab = new System.Windows.Forms.TabPage();
            this.githubTab = new System.Windows.Forms.TabPage();
            this.githubPane = new CodexVBE.GitHubPane();
            this.cancelOperation = new CodexVBE.ThemedButton();
            this.operationProgress = new System.Windows.Forms.ProgressBar();
            this.operationStatus = new System.Windows.Forms.TableLayoutPanel();
            this.importTab = new System.Windows.Forms.TabPage();
            this.previewImport = new CodexVBE.ThemedButton();
            this.connectionTab = new System.Windows.Forms.TabPage();
            this.gitConnectionView = new CodexVBE.GitConnectionView();
            this.gitChangesView = new CodexVBE.GitChangesView();
            this.gitHistoryView = new CodexVBE.GitHistoryView();
            this.gitBranchesView = new CodexVBE.GitBranchesView();
            this.gitCheckpointsView = new CodexVBE.GitCheckpointsView();
            this.gitConflictsView = new CodexVBE.GitConflictsView();
            this.gitImportView = new CodexVBE.GitImportView();
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(960, 780);
            this.MinimumSize = new System.Drawing.Size(700, 580);
            this.SuspendLayout();
            this.documentLabel.Text = "GitHub · VBA sources";
            this.documentLabel.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.documentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.documentLabel.AutoEllipsis = true;
            this.documentLabel.Name = "documentLabel";
            this.actions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actions.AutoSize = true;
            this.actions.Name = "actions";
            this.compare.Text = "Compare";
            this.compare.AutoSize = true;
            this.compare.Enabled = false;
            this.compare.Name = "compare";
            this.compare.Click += new System.EventHandler(this.Compare_Click);
            this.toolTips.SetToolTip(this.compare, "Compare live VBA with the last synchronized state without network access.");
            this.fetch.Text = "Fetch";
            this.fetch.AutoSize = true;
            this.fetch.Enabled = false;
            this.fetch.Name = "fetch";
            this.fetch.Click += new System.EventHandler(this.Fetch_Click);
            this.toolTips.SetToolTip(this.fetch, "Refresh remote commits and counts without changing VBA.");
            this.push.Text = "Push";
            this.push.AutoSize = true;
            this.push.Enabled = false;
            this.push.Name = "push";
            this.push.Click += new System.EventHandler(this.Push_Click);
            this.toolTips.SetToolTip(this.push, "Publish local commits on the chosen branch. Does not publish uncommitted changes.");
            this.pull.Text = "Pull and import";
            this.pull.AutoSize = true;
            this.pull.Enabled = false;
            this.pull.Name = "pull";
            this.pull.Click += new System.EventHandler(this.Pull_Click);
            this.toolTips.SetToolTip(this.pull, "Download and import sources. Refuses unsynchronized local changes and divergent histories.");
            this.restore.Text = "Restore VBA";
            this.restore.AutoSize = true;
            this.restore.Enabled = false;
            this.restore.Name = "restore";
            this.restore.Click += new System.EventHandler(this.Restore_Click);
            this.toolTips.SetToolTip(this.restore, "Restore the backup made before the last import if VBA has not changed since. Does not rewrite GitHub.");
            this.syncStatus.Text = "Branch not linked";
            this.syncStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.syncStatus.Name = "syncStatus";
            this.tabs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabs.Name = "tabs";
            this.branchesTab.Text = "Branches";
            this.branchesTab.Name = "branchesTab";
            this.branchesTab.Enabled = false;
            this.checkpointsTab.Text = "Checkpoints";
            this.checkpointsTab.Name = "checkpointsTab";
            this.checkpointsTab.Enabled = false;
            this.conflictsTab.Text = "Conflicts";
            this.conflictsTab.Name = "conflictsTab";
            this.conflictsTab.Enabled = false;
            this.changesTab.Text = "Git changes";
            this.changesTab.Name = "changesTab";
            this.historyTab.Text = "History";
            this.historyTab.Name = "historyTab";
            this.status.Text = "Link an existing GitHub repository to get started.";
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.Padding = new System.Windows.Forms.Padding(0, 6, 8, 0);
            this.status.Name = "status";
            this.githubTab.Name = "githubTab";
            this.githubPane.Name = "githubPane";
            this.cancelOperation.Name = "cancelOperation";
            this.operationProgress.Name = "operationProgress";
            this.importTab.Name = "importTab";
            this.githubTab.Text = "GitHub";
            this.githubPane.Dock = System.Windows.Forms.DockStyle.Fill;
            this.importTab.Text = "Import summary";
            this.cancelOperation.Text = "Cancel";
            this.cancelOperation.Enabled = false;
            this.cancelOperation.AutoSize = true;
            this.cancelOperation.Click += new System.EventHandler(this.CancelOperation_Click);
            this.operationProgress.Style = System.Windows.Forms.ProgressBarStyle.Marquee;
            this.operationProgress.Visible = false;
            this.operationStatus.Name = "operationStatus";
            this.operationStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.operationStatus.Margin = new System.Windows.Forms.Padding(0, 6, 0, 0);
            this.operationStatus.ColumnCount = 2;
            this.operationStatus.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.operationStatus.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.operationStatus.RowCount = 2;
            this.operationStatus.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.operationStatus.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 3F));
            this.operationStatus.SetColumnSpan(this.operationProgress, 2);
            this.operationProgress.Dock = System.Windows.Forms.DockStyle.Fill;
            this.operationProgress.Margin = new System.Windows.Forms.Padding(0);
            this.cancelOperation.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            this.cancelOperation.Visible = false;
            this.previewImport.Name = "previewImport";
            this.previewImport.Text = "Preview import";
            this.previewImport.AutoSize = true;
            this.previewImport.Click += new System.EventHandler(this.PreviewImport_Click);
            this.push.Margin = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.pull.Margin = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.connectionTab.Name = "connectionTab";
            this.connectionTab.Text = "GitHub repository";
            this.gitConnectionView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitChangesView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitHistoryView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitBranchesView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitCheckpointsView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitConflictsView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gitImportView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.connectionTab.Controls.Add(this.gitConnectionView);
            this.tabs.Controls.Add(this.connectionTab);
            this.changesTab.Controls.Add(this.gitChangesView);
            this.tabs.Controls.Add(this.changesTab);
            this.historyTab.Controls.Add(this.gitHistoryView);
            this.tabs.Controls.Add(this.historyTab);
            this.branchesTab.Controls.Add(this.gitBranchesView);
            this.tabs.Controls.Add(this.branchesTab);
            this.checkpointsTab.Controls.Add(this.gitCheckpointsView);
            this.tabs.Controls.Add(this.checkpointsTab);
            this.conflictsTab.Controls.Add(this.gitConflictsView);
            this.tabs.Controls.Add(this.conflictsTab);
            this.importTab.Controls.Add(this.gitImportView);
            this.tabs.Controls.Add(this.importTab);
            this.githubTab.Controls.Add(this.githubPane);
            this.tabs.Controls.Add(this.githubTab);
            this.layout.ColumnCount = 1;
            this.layout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowCount = 5;
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize, 0F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.layout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.layout.Controls.Add(this.documentLabel, 0, 0);
            this.layout.Controls.Add(this.syncStatus, 0, 1);
            this.layout.Controls.Add(this.actions, 0, 2);
            this.layout.Controls.Add(this.tabs, 0, 3);
            this.layout.Controls.Add(this.operationStatus, 0, 4);
            this.actions.Controls.Add(this.compare);
            this.actions.Controls.Add(this.fetch);
            this.actions.Controls.Add(this.push);
            this.actions.Controls.Add(this.previewImport);
            this.actions.Controls.Add(this.pull);
            this.actions.Controls.Add(this.restore);
            this.operationStatus.Controls.Add(this.status, 0, 0);
            this.operationStatus.Controls.Add(this.cancelOperation, 1, 0);
            this.operationStatus.Controls.Add(this.operationProgress, 0, 1);
            this.operationStatus.SetColumnSpan(this.operationProgress, 2);
            this.layout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.layout.Padding = new System.Windows.Forms.Padding(20);
            this.Controls.Add(this.layout);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "GitWindow";
            this.Text = "GitHub · VBAi";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.ShowInTaskbar = false;
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
